#!/bin/sh

# Open termminal
super + Return
	kitty

# Close focused window
super + q
	bspc node -c

# Reload sxhkd
super + Escape
	pkill -USR1 -x sxhkd

# Quit bspwm
super + alt + q
	bspc quit

# Switch focus
super + {h,j,k,l}
	bspc node -f {west,south,north,east}

# Move focused window
super + shift + {h,j,k,l}
	bspc node -s {west,south,north,east}
 
# Launch rofi
super + a
	/home/roman/.config/rofi/launchers/type-6/launcher.sh

# Switch to desktop 1-6
ctrl + {0-6}
    bspc desktop --focus ^{1-6}

# Move focused window to desktop 1-6
ctrl + shift + {0-6}
    bspc node -d ^{1-6}

# Audio
ctrl + t
    amixer set Master 5%+

# Focus next window with Tab
super + z
    bspc node -f next.local

