#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Set up monitor windows
bspc monitor DisplayPort-2 -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a discord desktop="^5"

# Set up monitors
xrandr --output DisplayPort-2 --mode 1920x1080 --rate 165 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rate 60 --rotate left --left-of DisplayPort-2

#Autostart applications
sxhkd &
polybar top &
kitty -e zsh -c "neofetch; exec zsh" &
nitrogen --restore &
picom --config ~/.config/picom/picom.conf &
dunst &
flameshot &
solaar --window=hide &
